### ISSUE TITLE
[SUGGESTİON] Replace Final object

### ISSUE THREAD

**Issue by akhundMurad** [ShahriyarR/py-read-once#1]
Hello, great repo! What do you think about replacing your custom Final class with [this](https://docs.python.org/3.8/library/typing.html#typing.final)
Maybe there is a reason why you didn't choose it?

**Comment by ShahriyarR** [comment]
Hello, you mean typing using Final? It is only okay for type checkers as:
`There is no runtime checking of these properties`.
What we need is actual runtime check.

The idea behind this Final class is to ensure that there is no 2 level subclassing.
You can inherit from ReadOnce, say you have DBPassword class, but you can not inherit from DBPassword it will rise a TypeError, ensuring that DBPassword will not be exposed further.

**Comment by akhundMurad** [comment]
Thanks for explanation, I forgot about runtime checking.
